### ISSUE TITLE
Judgmental Language clause perhaps too broad?

### ISSUE THREAD

**Issue by throwaway1973** [fantasylandinst/fcop#12]
The current version states: "Don't Communicate Judgmentally. You must not communicate the idea that any person, place, **thing, idea, or action** is superior or inferior to any other. Instead, talk about observations, analyses, models, and your own personal preferences." [emphasis added]

Since the FCOP's intended use cases presumably includes software development, I find myself somewhat confused by this point. For example, it naively seems to me that code containing a bug is inferior to code without the bug, and this seems like an opinion which if expressed might violate the FCOP. I'm guessing this sort of judgement was not intended to be covered by the clause, but naively it appears to be.

Suggested fix: Perhaps the wording could be changed to exclude technical topics? or perhaps "You must not communicate the idea that any person, place, thing, idea, or action is superior or inferior to any other, **except for beliefs which can reasonably be assumed to be universally true (software bugs are bad, 2+2 = 4, etc)**"

If the intent of this clause was to avoid a situation where feelings are hurt due to harsh feedback being given ("this code is awful", etc). Perhaps this could separately be addressed by a clause along the lines of "Be Polite" or similar?

Thanks again for making this project.

**Comment by throwaway1973** [comment]
Alternate suggested wording: 

"Don't **Hold Your Judgement Universal**. **Except in the case of facts which can reasonably understood to be both true and non-controversial (2+2=4, the earth revolves around the sun, etc), do** not communicate the idea that any person, place, thing, idea, or action is superior or inferior to any other **in an objective sense**. Instead, talk about observations, analyses, models, **scientific references, data sets,** and your own personal preferences. **By being more explicit about why you believe what you believe, and what evidence if refuted or provided would change your belief, you help facilitate evidence based decision making in the community.**"

(Though I freely admit the last sentence in that paragraph might count as me violating the rule. I'm not sure how universally accepted the idea of evidence based decision making is.)

**Comment by jdegoes** [comment]
From #25: 

> In particular, make it clear that a subjectively stated "best for purpose X" is not a judgmental communication, and include examples of things that do not qualify as judgmental communication because they refer to objectively measurable metrics.

The point really comes down to intrinsic versus intrinsic value: I think something is objectively and universally valuable; versus I think that something is valuable to me. Or I think that action X will lead to result Y, versus, I think you should do X because it's "morally superior". "PHP is a bad language" versus "PHP code bases have more defects, on average, than Haskell code bases, as measured by this study from 2011, or as measured by my personal experience."

It's possible to dramatically limit the scope of this clause by disallowing only *moralizing* and *insulting* language, which could be much more narrowly and clearly defined. Then judgmental language around other items would become permissible. Which is unfortunate, but way too many people are misunderstanding the clause as currently written, and it's unlikely it will be followed widely in practice.

**Comment by throwaway1973** [comment]
Getting a draft out to help me think about this concretely:

> **Communicate moral and aesthetic opinions as subjective**. If you can not reasonably infer your moral or aesthetic belief as universal ("death is usually bad", etc), do not state it as such or make universal statements which assume the belief.

> **Don't Shame.** Do not attempt to shame or otherwise force someone to change their beliefs. If another member's behavior is not in violation of the FCOP, do not attempt to shame or otherwise force them into changing it. You may ask them nicely to change and/or present arguments as to the benefits or factual correctness of some alternate belief or behavior, but you must also accept a "no" in response to you request as being valid (see "Don't Harass")

I believe you have more experience with this kind of behavior than I do, so I'm somewhat worried the above is missing the mark you intended to hit. That said I am confident the above edit would more than satisfy the cases that I mention above (2+2=4, etc).

**Comment by jdegoes** [comment]
The original clause is much broader, insisting that you may not speak of things as being intrinsically valuable (or value-less), but that instead you must speak of all value evaluations as being subjective. It's essentially the core idea in non-violent communication, where people are encouraged to speak in terms of observations and preferences.

That said, it's just causing too much confusion in people who don't have an NVC background. In addition, technically it's broader than it needs to be — "PHP is bad" is in fact judgmental, and either means or could be taken to mean that PHP has intrinsic negative value. While such statements are not really conducive to a (scientifically-rooted, data-driven) professional community, trying to forbid them is arguably trying to do to much.

My current thinking is splitting this into two aspects:

1. **No Moralizing**. Do not evangelize your moral system to others, whether communicating the idea that your moral system is superior to other moral systems, or expecting or intimidating people to profess or practice your moral system.
2. **No Denigration**. Do not communicate the idea that any physical or mental characteristic of any person (including religion, philosophy, politics, and values) is superior or inferior to any other. You may, however, communicate the idea that objective and testable statements held by someone do not accurately model reality.

This still leaves the door open to language flame wars, and so forth, but keeps things focused on professional topics rather than personal topics.
