### ISSUE TITLE
Stereotyping clause needs revision

### ISSUE THREAD

**Issue by jdegoes** [fantasylandinst/fcop#18]
The stereotyping clause is (or can be read as) a restriction on thought which is contrary to the FCOP goal of only prescribing external behavior. This needs to be revised so the stereotyping clause is clearly and unambiguously a restriction on _communication based on stereotypical assumptions_. For example, making a statement that implies you think a woman in clinic is a nurse rather than a doctor merely because she is a woman (etc.).

**Comment by throwaway1973** [comment]
Possible wording as hopeful food for thought: "Don't Stereotype. Treat everyone as unique. If you infer potentially controversial beliefs about a person based on their [perceived] membership in some group or category, do not communicate them to community members, or act in a way which causes those beliefs to be communicated."

(Added the 'controversial' clause above to support, for example, directing a person presenting as male who asked where the restroom is to the men's room rather than pausing to ask about their preferred gender before doing so.)

**Comment by throwaway1973** [comment]
While writing the above example, I felt like a less controversial one would have been preferable. However whenever I tried to come up with one it ended up coming out as "offering to get someone coffee without first asking if they drink coffee and if they are comfortable receiving gifts and if they feel comfortable being asked questions" or similar -- pedantic in the extreme.

I've come back to this ticket, and am sharing the experience now because on second thought I actually think the above is a *better* example of what I'm hoping to protect. If you really tried to make zero assumptions about other people, I think communication would become impossible. 'Controversial' is probably the wrong word, but hopefully you see the importance of finding a way to categorize the undesirable assumptions as separate from the necessary.

Well, either that or you see me more clearly for the pedant that I am...

More wording as food for thought: "Don't Stereotype. If you infer potentially controversial beliefs about a person based on their [perceived] membership in some group or category defined by their **gender, gender-expression, sexual-orientation, gender-orientation, race, ethnic origin, skin color, physical disability, intellectual disability, age, size, political views, religious views, philosophies, or beliefs**, do not communicate them to community members, or act in a way which causes those beliefs to be communicated"

Which I think is at least better than my previous suggestion. I've kept 'controversial' above since, well, I do think the restroom example remains valid. Thoughts?

**Comment by jdegoes** [comment]
Re: Controversial. Perhaps, "If you infer beliefs about a person (likely to be contested by that person) based on ...". Still a little squishy but at least suggests a means of formalization.

**Comment by throwaway1973** [comment]
Refactoring in response to your comment:

> *Dont' Stereotype.* Don't treat members differently on the basis of their membership in a professionally-orthogonal group, or communicate theories related to differences that may exist in professionally-orthogonal groups unless not doing so would violate professional and/or cultural norms.

(Note the theories clause is to allow, for example, a sickle cell anemia researcher from mentioning that race is related to the disease)

Which seems to roughly work, and protects both the bathroom example and my pedantic "excuse me, do you mind if I ask you a question?". I admit "professional and/or cultural norms" is squishy though, and opens the door to more restrictive COCs influencing the FCOP indirectly.

Although this is potentially more restrictive than "(likely to be contested by that person)", I'm having a hard time finding an example of communication worth protecting that's not currently allowed by professional and/or cultural norms.
