### ISSUE TITLE
prevent the encouragement of others to ostracise a community member

### ISSUE THREAD

**Issue by michaelficarra** [fantasylandinst/fcop#2]
I would like to feel safe from someone forming a personal campaign against me with the goal of doing professional harm.

**Comment by jdegoes** [comment]
This may be implied by #1, at least for Members encouraging other Members to ostracize other Members. 

I assume the goal here is to ensure that Members cannot encourage *non-Members* to ostracize Members? Or possibly beyond this, having a clause that, generally speaking, prohibits interfering with the ability of Members to pursue professions and participate in professional events and communities?

Such a clause would not have much power if limited to Active Participation. On the other hand, if the clause applied during Inactive Participation, it would be extremely powerful — preventing Members from ever interfering with the careers of other Members.

In the absence of this clause, someone could, in theory, launch a campaign to get you fired or banned from a community, and yet continue to participate in any FCOP community. We can prevent this by adding such a clause, but then it forces people to either philosophically agree with FCOP, or at least be willing to play along indefinitely in the rest of their lives. 

One can argue such a clause would decrease inclusiveness, since it would prevent people who violently disagree and work against the principles on which FCOP is based from participating in FCOP communities. Of course, one can argue that while it decreases inclusiveness, it's more consistent with the founding principles of FCOP, and might offer additional protections for Members.

I'll discuss the idea with others and post further comments here. In the meantime, if you have additional thoughts or clarifications, please feel free to share them.

**Comment by LeFey** [comment]
This one is tricky. While it's possible that we could allow for denial of entry to conference goers who have a history of brigading/doxxing to do so may be unnecessary and counterproductive. It could also become a double edged sword: people who defend themselves against attacks may technically violate some aspect of the rule.

Alternatively I would support a rule against recording other attendees without permission including attributing quotes to them on social media. "I overheard **some guy** at **some conf** say that he doesn't like bow ties, how rude!"

**Comment by jdegoes** [comment]
@LeFey I tend to agree. Also people who do not believe in a separation between professional / personal, may otherwise be persuaded if they participate in a healthy communication where such a separation is respected.

I think we already have the "recording" thing covered with the no name & shame clause, but can clarify it.
