### ISSUE TITLE
Extend prohibition against sabotage

### ISSUE THREAD

**Issue by jdegoes** [fantasylandinst/fcop#22]
Sabotage is currently restricted for moral, political, and ideological reasons, but rather than listing just these three, the restriction can be inverted so it is only permitted for meritocratic reasons (e.g. an employee's failure to perform requirements of the position).

**Comment by throwaway1973** [comment]
Can you perhaps explain a little bit why active sabotage is supported rather than the passive sabotage of removing active support (ie refusing to give a recommendation for the hypothetical ex-employee)? I am somewhat worried that meritocratic reasons will be hard to concretely draw a line around (though I would be *thrilled* to be proven wrong here). Perhaps such a definition can be discovered through discussion.

Alternate wording provided as food for thought: "Be Civil. Do not engage in criminal activity, and **take no actions which could bring negative consequence to** the community or member's careers for **behaviors not in violation of the FCOP.**" (this version is somewhat redundant with the "Don't Go Vigilante" section proposed in https://github.com/fantasylandinst/fcop/issues/17)

Please note that if the primary motivation for sabotage being allowed is not an employees failure to perform, but as a way of allowing members to warn other communities about behavior in violation of the FCOP, this is supported by the above.
