### ISSUE TITLE
Consider adding a transitive clause to the Inactive Participation section?

### ISSUE THREAD

**Issue by throwaway1973** [fantasylandinst/fcop#29]
Suggested clause: "Don't Transitively Transgress. Don't violate the FCOP in other communities governed by the FCOP."

I'm not sure if this is a good idea or not. If you expect you'll want to treat people who violate the FCOP in other communities differently, being explicit about it is probably a good idea. Maybe it's a bit too cute? This is related to the question of which kinds of sabotage are supported, currently being discussed at https://github.com/fantasylandinst/fcop/issues/22

**Comment by jdegoes** [comment]
> I'm not sure if this is a good idea or not. If you expect you'll want to treat people who violate the FCOP in other communities differently, being explicit about it is probably a good idea. Maybe it's a bit too cute? This is related to the question of which kinds of sabotage are supported, currently being discussed at #22

Agreed. It's closely related. I think an earlier version had something like this, but it was deleted under the rationale that their behavior in *other* FCOP communities is governed by *those* agreements and therefore does not need a clause in this community.

Now, #27 is more considered with the question, "Are there any circumstances in which we would pro-actively not allow someone to participate in the community because we believe they are incapable of following FCOP?" It's sort of a slippery slope, but if the answer to that question is yes, then conceivably, having willfully and recently violated FCOP in a separate community could be grounds for expulsion in another community.

**Comment by throwaway1973** [comment]
Having had 9 days to consider this, I'm now very strongly against a transitive clause.

The argument for, in Bayesian terms: if someone is already fruitfully participating in community A, and then something happens in community B... what's the probability they will act badly in community A? (Since we only care about behavior in our community)

The argument against, in logic: the FCOP assumes that behavior in one community can be kept separate from behavior in another. Why should this change if the other community is run by the FCOP? I can imagine that someone exists who can't follow the FCOP in a community for football fans, but can abide by the FCOP in a community about programming. If we expect they will abide by the FCOP in our community, we have no justification for excluding them.

Additionally, having to suffer N trials for 1 infraction seems like an unfair burden. It creates a sort of twitter mob situation in which all the communities you're in learn about any failings. I feel like this violates the privacy implied by the rest of the document.

I therefore think we should mention transitive violations as a possible consideration when someone _joins_ a new FCOP community (https://github.com/fantasylandinst/fcop/issues/27), but nothing more.

**Comment by jdegoes** [comment]
Agreed. Also: transitive violations imply trust between FCOP communities which is not a given. I would not want another FCOP community to have power over your own FCOP community. So depending on what comes out of #27, it's possible transitive violations need no special consideration.
