### ISSUE TITLE
You can literally murder a member and rejoin the community 5 years later

### ISSUE THREAD

**Issue by mjg59** [fantasylandinst/fcop#45]
Come on

**Comment by jdegoes** [comment]
No. If one commits murder, one is tried, sentenced, and "punished" by the court. FCOP makes no attempt to replace or augment the legal system.

Please refrain from nonconstructive and derogatory imperatives like, "Come on."

**Comment by mjg59** [comment]
But they are then free to rejoin the community and there is no mechanism for other community members to prevent this.

**Comment by mjg59** [comment]
Ok, let's use a different example. If a member of a community generating child-friendly content is jailed for paedophilia-related crimes directly related to their participation in the community, there is no mechanism that permits the community from forbidding them from rejoining the community after 5 years has passed.

**Comment by jdegoes** [comment]
@mjg59 

FCOP has a very clear provision stating that if leaders believe you will commit criminal offenses, they can deny you participation in the community. This is regardless of banishment. Banishment occurs only in connection with a consequence applied to the accused. If a member committed some crime, that member would be tried, sentenced, and punished through the legal system, and then the community leaders would have to decide whether they trust the member to not commit further crimes.

Rather than try to micro-regulate every possible situation, broad provisions allow leaders to exercise judgement on a case-by-case basis.

**Comment by mjg59** [comment]
This appears to be a loophole in the definition of consequences - if leaders can deny you participation in the community for an arbitrary length of time, how is this not equivalent to being able to banish people for more than 5 years?

**Comment by jdegoes** [comment]
@mjg59 

I am not sure that is a loophole. There is a difference between being prevented participation because of an estimated high likelihood of criminal activity, and being banned by an arbiter for a violation.

If community leaders do not feel that someone can follow the law, it is simply not safe to allow them into the space, regardless of whether they have previously violated FCOP.

Conversely, putting a cap on the consequence to a violation of FCOP which does not rise to the level of a criminal offense also seems sensible.

**Comment by mjg59** [comment]
@jdegoes This isn't explicit - the only description of a community being able to take actions other than those described under consequences is in the context of "if we become aware of behavior in another community that we believe implies a member may not abide by the terms and conditions of FCOP in the community, then we reserve the right to take proactive measures to protect other members". There is no description of it being possible to do so in response to behaviour that occurred *within* the community. The consequences section reads "In no case will the consequence for violating FCOP exceed banishment, unless the violation is also governed by separate contractual agreements or local laws", but it feels like this is intended to mean "If the local legal system forbids this, there may also be consequences under the local legal system" rather than "If the local legal system forbids this, the community may enact arbitrary consequences". If it's the latter then I think that needs clarifying.

**Comment by jdegoes** [comment]
@mjg59 The relevant section is in the definition of _civil_:

>  * **Civil**. We define civil individuals as individuals who, in our sole estimation, do not and will not engage in the following behaviors during _active participation_ or _inactive participation_:
>     * **Criminal Offenses**. Any illegal behavior considered a criminal offense in the community's country of jurisdiction.

The community is explicitly open to only _civil_ members. This seems pretty explicit although perhaps hidden because it's in the glossary?

**Comment by mjg59** [comment]
It's unclear - being civil is mentioned as a requirement in inactive participation, which makes being uncivil appear to be a violation, which limits the consequences to 5 years of banishment. If being uncivil actually permits greater consequences, that should be clarified.

**Comment by jdegoes** [comment]
@mjg59 I will open a new ticket.
