### ISSUE TITLE
FCOP doesn't no-platform white supremacists

### ISSUE THREAD

**Issue by EvanBurchard** [fantasylandinst/fcop#51]
Still allows white supremacists speaking potential at FCOP events. 

This is pretty much the only thing I would want out of the FCOP right now, given the history of the community. It's the biggest community problem you've had, and by not solving it through this CoC, you're reinforcing just how ok it is with you. 

People probably said it would be worse/set a bad precedent if you went the other way. That is wrong. I don't know why Douglas Crockford got no-platformed, but that was half a year ago, and nodevember survived. They're fine. And that was a much bigger name that they no-platformed.

Just say you don't tolerate hate speech. The professional/private dichotomy is impossible to actually create a wall between.

**Comment by throwaway1973** [comment]
It doesn't no-platform anyone who's willing to leave politics outside of the conference.

I'm not sure if you're aware of them, but http://degoes.net/articles/lambdaconf-inclusion and http://degoes.net/articles/lambdaconf-controversy were really helpful for my understanding the background motivation of the FCOP.

**Comment by EvanBurchard** [comment]
Yeah. Read both. I don't think tech or so many other dimensions of humanity are apolitical. 

"Everyone thinks they need to draw the line somewhere, and we decided not to", is just drawing the line around the status quo. It's not really a bold stance. I get why it might feel that way sometimes, but especially in the US, right now, with Thiel right there? Not so bold.

**Comment by jdegoes** [comment]
First, it's against FCOP guiding principles to ban people based on beliefs, thoughts, or values. Behavior in the community is what FCOP judges people by. I understand why you would want to ban people on other grounds, but other COCs cater to such sensibilities. Use one of them.

Second, if you were to create a COC that banned "white supremacists", it would have to allow CY to participate, since he is not a white supremacist (quote or you're lying, it's that simple).
