### ISSUE TITLE
Clarify "harm" in sabotage

### ISSUE THREAD

**Issue by jdegoes** [fantasylandinst/fcop#77]
There is no definition of "harm" in sabotage, which leaves it open to interpretation.

**Comment by mjg59** [comment]
Is factual, contextually accurate reporting of *any* behaviour something that should be considered harmful?

**Comment by jdegoes** [comment]
For reference, the current definition is as follows:

-----------------------

 * **Professional Sabotage**. We define _professional sabotage_ to be any behavior that does have or is intended to have the effect of harming a _member_'s career for any reason that is unrelated to the _member_'s performance in their professional duties, including but not limited to attempting to no-platform, blackball, or fire a _member_ because of physical or mental characteristics orthogonal to the performance of their professional duties; or encouraging others to engage in such behavior.

-----------------------

This does not include *any* behavior, but certainly does include any behavior that is related to _member_'s performance in their professional duties (which is very broad).

**Comment by jdegoes** [comment]
Upon looking at this definition more closely, I'd have to say that currently, pointing out incorrect code is _related_ to a member's performance in their professional duties, and would therefore be protected. Insulting someone while in a professional community would also be _related_ to the member's ability to perform their professional duties, and would therefore be protected.

**Comment by mjg59** [comment]
Note that professional sabotage does not make any reference to the provenance of the information. If community member A is a KKK leader, and community member B informs A's employers of this resulting in A being fired, this appears to meet the current definition of professional sabotage. Is this considered desirable?

**Comment by jdegoes** [comment]
>  this appears to meet the current definition of professional sabotage

This depends on whether or not being a "KKK leader" has implications on the performance of the professional duties of A, which it arguably could have depending on specifics.

Nonetheless, my current inclination is that the communication of factual personal details about someone (learned outside the community) would not count as professional sabotage regardless of the relationship to that person's professional duties or the fallout thereof.

**Comment by mjg59** [comment]
And if B learns the same information about A during active participation?

**Comment by jdegoes** [comment]
> And if B learns the same information about A during active participation?

Personal details learned during active participation are protected under _No Doxxing_. If someone at an event sees your laptop and notices you're in the LGBT in Tech Slack, for example, they cannot reveal that you are a member of this group.

**Comment by mjg59** [comment]
Are you genuinely equating membership of a support channel for a protected class with membership of an explicitly racist organisation?

**Comment by jdegoes** [comment]
I'm not equating anything, merely giving you an example of what _No Doxxing_ protects against.

**Comment by jdegoes** [comment]
Suppose a devout Muslim who believes that homosexuality is both a lifestyle choice and a terrible sin, as per one interpretation of the Quran: 

> Quran (7:80-84) - "...For ye practice your lusts on men in preference to women: ye are indeed a people transgressing beyond bounds.... And we rained down on them a shower (of brimstone)" - 

That's part of their religion, which is arguably a choice. You and I find it ridiculous but FCOP communities are not intended to impose my values or your values on people. There are other COCs designed for such purposes.

Thus even if one believes something is a choice and a horrible evil, they cannot on this basis break the _No doxxing_ rule without possibly facing arbitration. That's a feature, not a bug.

Do you understand why the ACLU defends the rights of Nazis to speak? It's not because they endorse the views of Nazis; rather, they find them repugnant. It's because if Nazis are denied the right to speak, then there will be another group which follows them (to say nothing of the warfare of disingenuously casting one's opponents as "literal Nazis", as has been done with Charles Murray and many others, for example); and so on, until what one is allowed to speak about and how one must speak about it is determined entirely by a fickle authoritarian government.

Similarly, FCOP allows participation by people you might find morally repugnant, so long as they behave themselves in the context of the community. I understand why people (including myself) are not very comfortable with this idea, but nonetheless, fundamentally your disagreement with FCOP stems from conflicting goals. You _wish_ to impose your moral system on others, because you believe it to be unerring and absolute, clearly and obviously superior to all those who disagree with you. Whereas, I and the other creators of FCOP wish to create an environment in which _no_ moral system is imposed on anyone, but in which people can come together for some _professional purpose_, regardless of their differences, under an agreed upon set of behavioral guidelines.

What you want cannot be satisfied by FCOP.

**Comment by mjg59** [comment]
The ACLU defends the rights of Nazis to speak because if a government restricts speech then there is *no* venue for that speech to occur - the government can simply forbid it, and the absence of free movement at the global scale means that individuals who wish to have a venue are unable to move to somewhere where it is permitted.

When we create individual communities, we have the privilege of being allowed to choose which forms of speech and which kinds of individual we wish to allow into those communities. This causes no problem because anyone excluded is free to set up a separate community that adheres to their own community standards. In contrast to government interference, we are simply engaging in the freedom of choosing who we associate with.

I do believe that my moral system is superior to that of people who believe that certain individuals are, by accident of birth, inherently inferior. I suspect you agree with me on that point. But you believe that these individuals are still able to provide meaningful contribution to a professional community, while I believe that (regardless of the moral disagreement I have with them) they will cause harm.

It is undeniable that racists cause harm to racial minorities, even in modern society. We see continued attacks on funding of schools in areas populated by racial minorities. We see individuals who overcome this denigrated as "diversity hires". We see physical and verbal intimidation intended to encourage them to adopt less visible roles. When you allow those same racists into a professional community, you validate their humanity and indicate to the population at large that you can be both racist and professionally successful. You reduce the social cost of racism. And by doing so, you increase the harm caused to racial minorities within not only your community, but surrounding communities.

FCOP is based on the premise that exclusion from professional communities hurts people. However, it is unrealistic to believe that members of minority groups will be willing to work with people who publicly denigrate them on a daily basis merely because the racists promise to put their racism aside while participating within that community. By accepting racists, you exclude their victims and deny them professional opportunities. By your own standards, you cause them harm.

Obviously this entire argument can be reframed as "Accepting LGBT individuals excludes strongly religious individuals", and yes, there's a sense in which it does. But you know that there's a difference between these cases - you find the religious objection to homosexuality ridiculous, but you don't find the idea that minorities object to racism ridiculous. And when you build a community, you (and everyone else) get to make that choice.

By arguing that you shouldn't make that choice, you don't create a net reduction in harm. You end up causing more harm to the least powerful. Do you really want to argue that that's a feature and not a bug?

**Comment by jdegoes** [comment]
> The ACLU defends the rights of Nazis to speak because if a government restricts speech then there is no venue for that speech to occur

I'd rather believe the ACLU [on this point](https://www.aclu.org/about/aclu-history#2):

> Historically, the people whose opinions are the most controversial or extreme are the people whose rights are most often threatened. Once the government has the power to violate one person's rights, it can use that power against everyone. We work to stop the erosion of civil liberties before it's too late.

The fundamental idea here is preventing "erosion" via the slippery slope.

A simple example will suffice: let's ban Nazis. Pretty uncontroversial, right? Sure, but now you have two separate issues: what is the definition of a Nazi (people will not agree on this definition); and how do you determine that someone satisfies this definition (people will not agree on the process, and even if they agree on the process, they will disagree on specific undesirable outcomes).

These issues mean that, if you ban Nazis, people will use the No-Nazi clause to ban people they strongly disagree with, even if those people are not Nazis. You may believe this would never happen, but that's because you have not been called a "literal Nazi" yet—whereas I have been called that, merely on grounds I refused to toe the party line.

If you really want to "ban Nazis", you'll end up creating a definition and evaluation criteria that few people will agree with (best case); or you'll end up creating a weapon by which people will purge their ideological enemies, regardless of whether or not those enemies are Nazis (worst case).

Moreover, there is no even remotely plausible of "Nazi" in which, say, Curtis Yarvin is a Nazi. So if you ban Nazis, you'll still end up with lots of people like Curtis Yarvin, who believe that, while individual differences trump everything else, the mean of IQ test scores differs by "race". 

Ultimately, banning Nazis is not sufficient. In order to exclude precisely the people you want to exclude, your policy must be equivalent to, "We will exclude anyone we deem to be sufficiently bad or unwelcoming to those we wish to include." i.e. you base it on your subjective feelings about the person and your subjective estimation of what effect the person will have on those you wish to include (which feelings can be trivially manipulated by social media, by the way).

Generally communities run by this policy are called "support groups", and they serve functions that are very important to their members. I support these communities, but I also believe it's critical for civility and peace in a pluralistic society for there to exist communities (such as libraries, stores, events, and workplaces) in which people who do not share the same ideology can nonetheless occupy the same space for common or mutually beneficial interests.

> When you allow those same racists into a professional community, you validate their humanity and indicate to the population at large that you can be both racist and professionally successful.

These are not arguments, they are hand-waving assertions. Watch how easy it is to make these assertions: *when you sell food to a racist, you validate their humanity and indicate to the population at large that you can be both racist and engage in commerce.*

See how easy it is to assert whatever I want? These are not arguments, they are hand-wavy moral posturing designed to justify the acquisition and exercise of power.

Show me a large, controlled, double-blinded study that demonstrates the inclusion of people who satisfy your definition of "racist" in professional communities increases the incidence of "racism" in society. In fact, actual studies show the exact opposite — that prejudice is reduced by exposure to the other in the context of a common goal (Monteith, Deneen, & Tooman, 1996, Desforges et al., 1991; Dovidio & Gaertner, 1999; Sherif, Harvey, White, Hood, & Sherif, 1988).

But let's ignore all the data for a second (since even more studies suggest if you see prolific and quality data that contradicts your view, you will merely double down on your view). Let's say you convince me to create support groups filled with people I like, rather than pluralistic professional communities. Will you have succeeded in your goal?

I think not. Because while I would exclude Nazis, LGBTQ bigots, misogynists, misandrists, racists, and lots of other people, I would also explicitly exclude anyone who is not a realist and an atheist, as well as anyone I deem insufficiently illiberal — for example, anyone who believes in "subhumans", and who refuses to "validate the humanity" of other people. (In my world view, there are no "bad" humans who need "punishment", only "broken" humans who need "help".)

In the end, my support group will consist of me and 4 other people. We'll have a great time, I'm sure, but it will be more akin to a pajama party than a professional community. It will certainly not be consistent with, say, a non-profit's goal to educate people with the goal of providing much-needed careers to lower income and unemployed individuals.

Some things I want to do are better enabled by support groups; and others are better enabled by professional communities following FCOP. I don't collapse all my goals into one.

> But you know that there's a difference between these cases - you find the religious objection to homosexuality ridiculous, but you don't find the idea that minorities object to racism ridiculous.

Actually, some minorities are racist, and others are sexist, and still (many) others are homophobic and transphobic. There are not two separate communities of "minorities" and "oppressors", but rather an extremely large number of overlapping communities. For example, in the case of a homophobic, transphobic woman of color, and a misogynist gay white male, which do you allow into your community? If you can answer that one, then rinse & repeat for all other possible combinations.

You may wish to play such games of power and signaling, deciding who is more worthy of inclusion into the Great Pajama Party. I do not — at least, not for the professional communities I create and develop. There is a place in this world for communities that do not enforce ideological purity tests on their members — in addition to a place for communities that do — and FCOP is a useful COC for such communities (but not a useful COC for other types of communities).

**Comment by mjg59** [comment]
> The fundamental idea here is preventing "erosion" via the slippery slope.

You've already established a slippery slope within FCOP - the community is free to decide if an individual has engaged in past behaviour that indicates they may engage in criminal acts in future and can pro-actively ban them. A community that does so inappropriately would be judged as corrupt. But there's no explicit set of tests there - it's based on the beliefs of the existing community. Adding additional critera there (such as the community being free to pro-actively bar racists) doesn't create an additional slippery slope. A community with such a criterion could certainly abuse it to exclude anyone that they don't like, but as you've pointed out there's no way for the FCOP to bind its communities either: communities can enforce their code of conduct in arbitrary malicious ways, and there's no way to prevent that. The problem here isn't the existence of exclusionary criteria, it's the individuals enforcing them.

> when you sell food to a racist, you validate their humanity and indicate to the population at large that you can be both racist and engage in commerce.

I mean yes, in a sense you do. That's why various people will choose not to do business with racists. But I don't think that racism should be a capital crime, so I'm glad that enough people do do business with them that they don't starve to death.

> Show me a large, controlled, double-blinded study that demonstrates the inclusion of people who satisfy your definition of "racist" in professional communities increases the incidence of "racism" in society.

That's not the argument I made. In a world where racism is still prevalent, do you believe that a community that is accepting of racists (as long as they don't engage in that racism within the community) will be more, equally or less attractive to the victims of those racists?

> Let's say you convince me to create support groups filled with people I like

But I don't want that. I'm a member of multiple communities with members who hold positions I find abhorrent. But there's a difference between holding positions I find abhorrent and engaging in behaviour that hurts oppressed groups, and I can choose communities that exclude the latter while tolerating the former.

> For example, in the case of a homophobic, transphobic woman of color, and a misogynist gay white male, which do you allow into your community?

Neither? Those all seem like legitimate exclusionary criteria.

But you didn't respond to my fundamental point here. While you try to define "harm" in this specific case, you're neglecting the professional harm caused to members of oppressed groups by giving them the choice of either working alongside people who openly (outside the community) argue that they should be excluded from society, or finding a different community. That harm is real, but currently entirely unaddressed by FCOP. Why is that?

**Comment by jdegoes** [comment]
> Adding additional critera there (such as the community being free to pro-actively bar racists) doesn't create an additional slippery slope.

Judging people by their thoughts instead of their behavior in the community is explicitly against a founding principle of FCOP, summarized in the guiding principles:

> Policies may only dictate behavior, not thought or other internal characteristics.

There is a very clear line between banning people who present a physical harm to other participants of the community, and banning people for thoughts they hold inside their head which they do not express during participation.

> In a world where racism is still prevalent, do you believe that a community that is accepting of racists (as long as they don't engage in that racism within the community) will be more, equally or less attractive to the victims of those racists?

I think that attempting to describe an entire class of people as a "victim" that thinks and acts with one hivemind is racist. But I wouldn't exclude you from participating in an FCOP community just over that.

People are individuals, not group hiveminds, and different individuals will make whatever choices they feel comfortable with.

> Neither? Those all seem like legitimate exclusionary criteria.

Well, this confuses me since you said the main point is to create an environment welcoming of minorities, yet here you are saying you wish to exclude minorities who think bad thoughts.

I think what you *really meant* was that the main point is to create an environment welcoming of minorities *who think exactly like you do*.

> While you try to define "harm" in this specific case, you're neglecting the professional harm caused to members of oppressed groups by giving them the choice of either working alongside people who openly (outside the community) argue that they should be excluded from society, or finding a different community. That harm is real, but currently entirely unaddressed by FCOP. Why is that?

We've already established you will exclude members of oppressed groups if they don't think your thoughts, so why are we still on this point?

You can argue my ugly mug makes you too afraid to be in the same building with me. FCOP will only guarantee that I treat you well, not that you won't be terrified by my face.

**Comment by mjg59** [comment]
> There is a very clear line between banning people who present a physical harm to other participants of the community, and banning people for thoughts they hold inside their head which they do not express during participation.

There is! Just like there's a very clear line between banning people who denigrate others based on aspects of who they are and banning people who denigrate others based on what they believe. You can ban homophobes without banning people who believe in small government.

(I'll note that, as written, the FCOP allows you to forbid someone membership based on a belief that they may commit *any* criminal act, even during inactive participation - there's clearly a difference between banning people who present a physical risk to other participants of the community and banning people who use marijuana for pain relief, but you've written something that allows communities to go down the slippery slope of banning the latter)

> People are individuals, not group hiveminds, and different individuals will make whatever choices they feel comfortable with.

Do you agree that there will be potential members of a community who will feel more comfortable not being part of that community if the community welcomes individuals who describe them as genetically inferior?

> Well, this confuses me since you said the main point is to create an environment welcoming of minorities, yet here you are saying you wish to exclude minorities who think bad thoughts.

I want to exclude anyone whose behaviour exposes their intolerance of people for who they are, not what they believe. Again, that seems like a clear line.

> We've already established you will exclude members of oppressed groups if they don't think your thoughts

No, we've established that I would (given the choice) exclude members of oppressed groups if they would in turn oppress other oppressed groups.

> You can argue my ugly mug makes you too afraid to be in the same building with me. FCOP will only guarantee that I treat you well, not that you won't be terrified by my face.

That would be pretty irrational on my part, and it's unreasonable to ask you to change your appearance (something fundamental to who you are) in order to reduce any harm that I suffer as a result. Do you think it's irrational for someone to wish to avoid spending time with people who have publicly and earnestly argued that their race makes them inferior? Do you think it's unreasonable to ask those people to stop making that argument in order to stop causing the resulting harm?

**Comment by jdegoes** [comment]
> There is! Just like there's a very clear line between banning people who denigrate others based on aspects of who they are and banning people who denigrate others based on what they believe. You can ban homophobes without banning people who believe in small government.

Just like there's a very clear line between banning people based on their expressed hair style, and banning people based on their shoe size. You can ban blondes without banning people who require extra large shoes.

A COC can be or do anything you want it to be. FCOP is designed for professional communities, not social ones or support groups, and is designed to allow people who think differently to still work together in a professional capacity even if their ideologies are incompatible.

I think you would like the [Maitria code of welcoming conduct](https://github.com/maitria/code-of-welcome/blob/master/coc.md). FCOP exists at a different location in the landscape of potential COCs.

> there's clearly a difference between banning people who present a physical risk to other participants of the community and banning people who use marijuana for pain relief, but you've written something that allows communities to go down the slippery slope of banning the latter

Useful feedback. That's fixed in the current version. 

> Do you agree that there will be potential members of a community who will feel more comfortable not being part of that community if the community welcomes individuals who describe them as genetically inferior?

I do think there may exist some conservative Muslims who wouldn't be comfortable in the same room with you, because you'd look down on them for their literal interpretation of the Quran. I also think there exist many who are confident about who they are and don't give a crap about what you think.

> I want to exclude anyone whose behaviour exposes their intolerance of people for who they are, not what they believe. Again, that seems like a clear line.

It's very clear if you're the one who gets to decide "who they are" versus "what they believe". You do know political affiliation is hereditable, right? I'm a liberal because of my higher openness and agreeableness. I didn't chose to have those traits. Why do you want to punish me for them?

> No, we've established that I would (given the choice) exclude members of oppressed groups if they would in turn oppress other oppressed groups.

Since there are hundreds of thousands of oppressed groups and huge variety within and across them, this basically means you will exclude almost all minorities. I'm not sure what kind of social change you're trying to achieve with these exclusionary policies.

**Comment by mjg59** [comment]
> Just like there's a very clear line between banning people based on their expressed hair style, and banning people based on their shoe size. You can ban blondes without banning people who require extra large shoes.

You absolutely can, but why would you? The line that you've chosen to enforce in FCOP is entirely arbitrary and does not preclude the existence of other hard lines that also stop short of permitting the exclusion of individuals based on their political beliefs.

> Useful feedback. That's fixed in the current version.

Not really. Victim isn't described - some would argue that by using marijuana, I'd be establishing it as normal behaviour, reducing social barriers to others choosing to do the same and (as a result) becoming hooked on harder drugs and ruining their life. I think this argument is nonsense, but would a community that used it be corrupt? There's still a slippery slope here - you have to trust that communities won't take advantage of it, in the same way that you have to trust that communities won't choose to arbitrarily refuse membership to people with hair longer than a certain length.

>> Do you agree that there will be potential members of a community who will feel more comfortable not being part of that community if the community welcomes individuals who describe them as genetically inferior?

>I do think there may exist some conservative Muslims who wouldn't be comfortable in the same room with you, because you'd look down on them for their literal interpretation of the Quran. I also think there exist many who are confident about who they are and don't give a crap about what you think.

Why do you keep refusing to actually answer this question? I don't look down on people for literal interpretations of religious texts (I grew up in an extremely religious environment), even if I disagree with them.

> It's very clear if you're the one who gets to decide "who they are" versus "what they believe". You do know political affiliation is hereditable, right? I'm a liberal because of my higher openness and agreeableness. I didn't chose to have those traits. Why do you want to punish me for them?

If there's expert consensus to that end, that's an interesting conversation to have.

> Since there are hundreds of thousands of oppressed groups and huge variety within and across them, this basically means you will exclude almost all minorities. I'm not sure what kind of social change you're trying to achieve with these exclusionary policies.

In practice this doesn't happen?

**Comment by jdegoes** [comment]
> You absolutely can, but why would you? The line that you've chosen to enforce in FCOP is entirely arbitrary and does not preclude the existence of other hard lines that also stop short of permitting the exclusion of individuals based on their political beliefs.

The line may not be to your liking, but it's not arbitrary. It's the most inclusive definition that ensures all the behavior inside a community that is necessary for professionals to productively work toward shared goals independent of their (likely) incompatible values outside work.

> Victim isn't described - some would argue that by using marijuana

Nope. _Victimless crime_ has a long history of referring to laws against drug pleasure and sexual pleasure. Such things can be clarified further in a "test suite" if it turns out to be necessary.

> I don't look down on people for literal interpretations of religious texts (I grew up in an extremely religious environment), even if I disagree with them.

But you would exclude them from professional communities for their literal interpretation of their religious texts, even if they can treat others professionally while in those communities?

> If there's expert consensus to that end, that's an interesting conversation to have.

There is indeed expert consensus. Would banning people for their genetics be more objectionable to you?

> In practice this doesn't happen?

It'll only happen if you're consistent in enforcing your stated desire to exclude wrongthink regardless of who exhibits it. Homophobia and transphobia, for example, are prevalent in numerous minority communities.

**Comment by mjg59** [comment]
>  It's the most inclusive definition that ensures all the behavior inside a community that is necessary for professionals to productively work toward shared goals independent of their (likely) incompatible values outside work.

This is an unsupported assertion.

> Nope. Victimless crime has a long history of referring to laws against drug pleasure and sexual pleasure. Such things can be clarified further in a "test suite" if it turns out to be necessary.

The term victimless crime is used by different people to mean different things (eg, is copyright infringement a victimless crime?). In the absence of an actual definition, you've left it up to individual communities to make an arbitrary decision.

> But you would exclude them from professional communities for their literal interpretation of their religious texts, even if they can treat others professionally while in those communities?

Depending on how they express that literal interpretation of their religious texts outside the community, yes.

> There is indeed expert consensus

I'd be fascinated to read it.

> Would banning people for their genetics be more objectionable to you?

Obviously.

> Homophobia and transphobia, for example, are prevalent in numerous minority communities.

And members who express that homophobia and transphobia shouldn't be welcomed into communities.

But, again, you've failed to answer the fundamental question here. Do you agree that there will be potential members of a community who will feel more comfortable not being part of that community if the community welcomes individuals who describe them as genetically inferior? If you do, are they harmed by that presence? If not, why not?

**Comment by jdegoes** [comment]
> This is an unsupported assertion.

True, but I'm not running around Github trying to persuade others of my views. You think this definition is _not_ the most inclusive one that ensures professional behavior in a pluralistic society? 

OK, tell me why I should listen. Using double-blinded, large-scale, controlled studies, preferably.  

> In the absence of an actual definition, you've left it up to individual communities to make an arbitrary decision.

I'm happy to lock this down further if you think it's a _legitimate_ concern and are not just trolling here. I don't certainly don't want marijuana use, copyright infringement, prostitution, and numerous other "victimless crimes" to lead to exclusion on grounds of incivility, since they don't materially risk the person or property of other community members.

> Depending on how they express that literal interpretation of their religious texts outside the community, yes. [...] And members who express that homophobia and transphobia shouldn't be welcomed into communities.

These exclusionary practices could be construed as targeting numerous minority groups. Why are you so eager to exclude minorities from your communities? Why not create a more inclusive, welcoming community designed first and foremost to serve the needs of working professionals? Why does everything have to be about imposing your and my values onto others?

> But, again, you've failed to answer the fundamental question here. Do you agree that there will be potential members of a community who will feel more comfortable not being part of that community if the community welcomes individuals who describe them as genetically inferior? If you do, are they harmed by that presence? If not, why not?

I think it highly probably there exist potential members of a community who do not want to participate in that community because it does not actively exclude those they do not like (for whatever reason), even if those people are required to behave themselves professionally. I do not grant that individuals can be "harmed" merely by residing in the same space (online or physical) as someone they don't like, at least, not for any meaningful definition of the word "harm".

Now your turn: as a white male, do you have the ability to exist in the same space as those who look down on you, for example, a Muslim who believes you're a morally repugnant abomination to Allah, or a member of the Nation of Yahweh who believes you are inferior to her?

**Comment by mjg59** [comment]
> OK, tell me why I should listen. Using double-blinded, large-scale, controlled studies, preferably.

Do you have a double-blinded, large-scale controlled study that supports every decision you've made here? That seems unlikely, since I'd expect them to have been cited otherwise. This document isn't fundamentally truer than any other code of conduct.

> I'm happy to lock this down further if you think it's a legitimate concern and are not just trolling here. I certainly don't want marijuana use, copyright infringement, prostitution, and numerous other "victimless crimes" to lead to exclusion on grounds of incivility, since they don't materially risk the person or property of other community members.

I think that a community of professional film producers may argue that copyright infringement is anything but a victimless crime. If such a community adopted FCOP, would it be inappropriate for them to refuse entry to people who write articles about how to break various copy protection mechanisms? They'd certainly argue that this is someone who's harmed the property of other community members.

> These exclusionary practices could be construed as targeting numerous minority groups. Why are you so eager to exclude minorities from your communities?

Anti-semites are (I hope) a minority, but I'm enthusiastic about excluding them because I'm enthusiastic about including people who are unwilling to spend time with anti-semites. Basically, I can have one or the other - welcoming anti-semites *is* going to drive away others. If being unable to participate in activities that further someone's professional career is harm (as is clear from the definition of professional sabotage, which is why we're talking about this in the first place) then I can choose to cause harm anti-semites or I can choose to cause harm to those of Jewish heritage. Since I am forced to make this choice, I choose to cause harm to the anti-semites.

> I think it highly probably there exist potential members of a community who do not want to participate in that community because it does not actively exclude those they do not like (for whatever reason), even if those people are required to behave themselves professionally. I do not grant that individuals can be "harmed" merely by residing in the same space (online or physical) as someone they don't like, at least, not for any meaningful definition of the word "harm".

The question isn't whether they're harmed by being in the same room (although I suspect victims of racially motivated attacks who suffer from PTSD may strongly disagree with your argument that they're not harmed by being in a room with members of the group that attacked them), the question is whether they suffer harm if they are unable to participate in the community. The FCOP makes it clear that the answer is yes.

> as a white male, do you have the ability to exist in the same space as those who look down on you, for example, a Muslim who believes you're a morally repugnant abomination to Allah, or a member of the Nation of Yahweh who believes you are genetically inferior to her?

Yes, because I live somewhere where they have no meaningful power over me as a result of those beliefs. But if you asked me in the 1920s whether I felt I had the ability to exist in the same space as, say, a number of KKK members who kept publicly expressing strong anti-Catholic sentiments, the answer would be very different.
